export const SIGN_UP = "SIGN_UP"
export const SIGN_IN =  "SIGN_IN"
export const GET_PRODUCT = "GET_PRODUCT"
export const CART_ITEM = "CART_ITEM"
export const GET_CART_ITEM = "GET_CART_ITEM"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"